---

- name: Install grafana
  yum:
    name: https://dl.grafana.com/enterprise/release/grafana-enterprise-{{ GRAFANA_VERSION }}.{{ GRAFANA_ARCH }}.rpm
    state: present
  notify:
    - restart grafana

- name: Copy grafana files
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: true
  with_items:
    - { source: "etc/grafana/grafana.ini.j2", destination: "/etc/grafana/grafana.ini", mode: "0644", user: "root", group: "root"}
  notify:
    - restart grafana

- name: Ensure grafana is running
  service:
    name: grafana-server
    enabled: yes
    state: started